---
- name: Installation install software-properties-common
  apt: name=software-properties-common

- name: "Repo PHP {{ php_version }}"
  apt_repository:
    repo="ppa:ondrej/php"

- name: "Updating the repo"
  apt: update_cache=yes

- name: Installation PHP {{ php_version }}
  apt: name=php{{ php_version }} state=present
- name: install other
  apt:
    pkg:
      - php{{ php_version }}-bcmath
      - php{{ php_version }}-mysql
      - php{{ php_version }}-mbstring
      - php{{ php_version }}-xmlrpc
      - php{{ php_version }}-xml
      - php{{ php_version }}-zip
      - php{{ php_version }}-intl
      - php{{ php_version }}-soap
      - php{{ php_version }}-curl
      - php{{ php_version }}-dev
      - php{{ php_version }}-fpm
      - php{{ php_version }}-cli
    state: present
    update_cache: yes
